# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: fundai
      POSTGRES_USER: fundai
      POSTGRES_DB: fundai
